### ISSUE TITLE
error "'phi-node-folding-threshold' registered more than once"

### ISSUE THREAD

**Issue by hughperkins** [jrprice/Oclgrind#137]
Hi James,

Since I have a Mac now, I'm looking for an easy way to run opencl stuff on ubuntu 16.04 on it. It occurred to me to dabble in using oclgrind for this. I get the following error.  I'm not sure what this means, why I get it, nor how to solve it?

```
$ oclgrind ./cuda_sample
: CommandLine Error: Option 'phi-node-folding-threshold' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```
Thoughts?

**Comment by jrprice** [comment]
This sort of thing happens when you try and combine multiple libraries that are using LLVM, which has some static initialization functions to register passes that end up breaking if they're called multiple times from the same process. It tends to crop up a lot with these open source implementations of OpenCL, and causes problems for [pocl](https://github.com/pocl/pocl/issues/474) and [beignet](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=852746) as well.

I'm not really sure what the fix is. You could try linking to LLVM statically from Coriander, which usually seems to be the solution.

**Comment by hughperkins** [comment]
Hmmm, interesting. At least I know what to google for now :-) . This looks interesting: https://github.com/kitech/ruby-jit-qt/commit/244483ce210f7d03ed80979d0aff6c02292b5370

**Comment by hughperkins** [comment]
(oh. perhaps I can simply not link to llvm in my executable at all ???)

**Comment by hughperkins** [comment]
Seems it comes from here: http://llvm.org/docs/doxygen/html/CommandLine_8cpp_source.html

```
  void addLiteralOption(Option &Opt, const char *Name) {
00112     if (!Opt.hasArgStr()) {
00113       if (!OptionsMap.insert(std::make_pair(Name, &Opt)).second) {
00114         errs() << ProgramName << ": CommandLine Error: Option '" << Name
00115                << "' registered more than once!\n";
00116         report_fatal_error("inconsistency in registered CommandLine options");
00117       }
00118     }
00119   }
```

**Comment by hughperkins** [comment]
James, just noticed, coriander is already linked statically:

```
~/git-local/tensorflow-dev/third_party/coriander/build (master|△1) $ otool -L libcocl.dylib 
libcocl.dylib:
	/Users/hugh2/git-local/tensorflow-dev/third_party/coriander/build/libcocl.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/hugh2/git-local/tensorflow-dev/third_party/coriander/build/libeasycl.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
	/Users/hugh2/git-local/tensorflow-dev/third_party/coriander/build/libclblast.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/hugh2/git-local/tensorflow-dev/third_party/coriander/build/libclew.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
```

```
nm libcocl.dylib | grep -i llvm >out.txt
```
out.txt: https://gist.github.com/hughperkins/6e43ea48599fbfbcdafa496c948688e3

**Comment by illuhad** [comment]
Hi,

I don't know if this applies to the problem on your system as well, but there is currently a similar problem on Arch Linux (it's complaining about a different option, but otherwise same error message).

On Arch Linux, the problem seems to be that cmake always tries to link LLVM statically, but the clang libraries are linked dynamically against LLVM. Consequently, the LLVM libraries are loaded multiple times. I don't know how to tell the cmake llvm scripts to link dynamically to LLVM (it seems they link statically no matter what?), but it works if `set(LLVM_LIBS -lLLVM-6.0)` is added to the CMakeLists.txt file.

**Comment by BeauJoh** [comment]
> James, just noticed, coriander is already linked statically, with llvm:
> 
> ```
> [somewhere]/coriander/build (master|△1) $ otool -L libcocl.dylib 
> libcocl.dylib:
> 	[somewhere]/coriander/build/libcocl.dylib (compatibility version 0.0.0, current version 0.0.0)
> 	[somewhere]/coriander/build/libeasycl.dylib (compatibility version 0.0.0, current version 0.0.0)
> 	/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
> 	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
> 	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
> 	[somewhere]/coriander/build/libclblast.dylib (compatibility version 0.0.0, current version 0.0.0)
> 	[somewhere]/coriander/build/libclew.dylib (compatibility version 0.0.0, current version 0.0.0)
> 	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
> ```
> ```
> nm libcocl.dylib | grep -i llvm >out.txt
> ```
> out.txt: https://gist.github.com/hughperkins/6e43ea48599fbfbcdafa496c948688e3

Hi @hughperkins and @jrprice,

I'm also trying to use both your tools (coriander and oclgrind) together.
My hope is to use coriander to evaluate the architecture-independent feature-spaces between CUDA and OpenCL versions of the same algorithm.
I wish to examine language-agnostic architecture-independent features of kernels.
I've written a plugin to Oclgrind to collect these features and is the bulk of my PhD.
However, I've hit the exact same error you've both described.

`
> EXTRA_LINKER_ARGS="-L/libscibench/lib/ -llsb" $COCL -I/libscibench/include -fPIC ./gaussian_cuda_version/gaussian.cu -o gaussian_cocl
> CL_GPUOFFSET=0 CL_PLATFORMOFFSET=0 $OCLGRIND_BIN --workload-characterisation ./gaussian_cocl matrix4.txt
: CommandLine Error: Option 'phi-node-folding-threshold' registered more than once!
`

I can confirm that both Oclgrind and coriander have been statically linked to LLVM.

`
> ldd libcocl.so
        linux-vdso.so.1 =>  (0x00007fffe955b000)
        libeasycl.so => /coriander/coriander/newbuild/./libeasycl.so (0x00007f649b33b000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f649b133000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f649af2f000)
        libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f649ad06000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f649aae9000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f649a7e0000)
        libclew.so => /coriander/coriander/newbuild/./libclew.so (0x00007f649a5da000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f649a258000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f649a042000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6499c78000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f649bd56000)
`

And

`
> ldd liboclgrind.so
        linux-vdso.so.1 =>  (0x00007ffcfafb3000)
        libreadline.so.6 => /lib/x86_64-linux-gnu/libreadline.so.6 (0x00007fe43508b000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fe434e83000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe434c7f000)
        libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007fe434a56000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe434839000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fe434530000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fe4341ae000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fe433f98000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe433bce000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fe4375bd000)
`

I've gone crazy and have tried to force the same version of LLVM -- since subjectively based on James' feedback 4.0 seems kind of buggy.

I can't get coriander to build with any other LLVM version but 4.0.
3.9 will build but when trying to compile my test example is missing '__clang_cuda_builtin_vars.h'
`
> EXTRA_LINKER_ARGS="-L/libscibench/lib/ -llsb" $COCL -I/libscibench/include -fPIC ./gaussian_cuda_version/gaussian.cu -o gaussian_cocl
In file included from <built-in>:2:
In file included from /root/coriander/include/cocl/fake_funcs.h:45:
/root/coriander/include/cocl/__clang_cuda_runtime_wrapper.h:85:10: fatal error:
      '__clang_cuda_builtin_vars.h' file not found
#include "__clang_cuda_builtin_vars.h"
         ^
1 error generated.
` 
while building coriander with LLVM 5.0 yields:
`
In file included from /coriander/coriander/src/mutations.cpp:15:
In file included from /coriander/coriander/include/cocl/mutations.h:3:
/coriander/coriander/soft/llvm-5.0/include/llvm/IR/Module.h:344:50: error:
      non-constant-expression cannot be narrowed from type 'long' to 'size_t'
      (aka 'unsigned long') in initializer list [-Wc++11-narrowing]
    SmallVector<Type*, sizeof...(ArgsTy)> ArgTys{Args...};
                                                 ^~~~
/coriander/coriander/soft/llvm-5.0/include/llvm/IR/Module.h:353:12: note: in instantiation
      of function template specialization 'llvm::Module::getOrInsertFunction<long>'
      requested here
    return getOrInsertFunction(Name, AttributeList{}, RetTy, Args...);
           ^
/coriander/coriander/src/mutations.cpp:49:12: note: in instantiation of function template
      specialization 'llvm::Module::getOrInsertFunction<long>' requested here
        M->getOrInsertFunction(
           ^
/coriander/coriander/soft/llvm-5.0/include/llvm/IR/Module.h:344:50: note: insert an
      explicit cast to silence this issue
    SmallVector<Type*, sizeof...(ArgsTy)> ArgTys{Args...};
                                                 ^~~~
                                                 static_cast<size_t>( )
1 error generated.
`

When I compile Oclgrind to use LLVM 4.0 instead of 3.9:
`
> export PATH="/coriander/coriander/soft/llvm-4.0/bin:$PATH"
> cmake $OCLGRIND_SRC -DUSE_LEVELDB=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLLVM_DIR=/coriander/coriander/soft/llvm-4.0/lib/cmake -DCLANG_ROOT=/coriander/coriander/soft/llvm-4.0/lib -DCMAKE_INSTALL_PREFIX=$OCLGRIND
`
We get notified of a bug in LLVM 4.0 with oclgrind -- confirmation bias on my end.
`
-- Using LLVMConfig.cmake in: /coriander/coriander/soft/llvm-4.0/lib/cmake/llvm
CMake Warning at CMakeLists.txt:63 (message):
  There is a known bug with LLVM 4.0.0 that will cause Oclgrind to fail on
  some kernels with a message about `addrspacecast`.  Use LLVM 3.9 or 4.0.1+
  if possible.
`
But at least it links and runs. Unfortunately, we run into the same:
`
> CL_GPUOFFSET=0 CL_PLATFORMOFFSET=0 $OCLGRIND_BIN --workload-characterisation ./gaussian_cocl matrix4.txt
: CommandLine Error: Option 'phi-node-folding-threshold' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
`

👎 

Without looking into the llvm source code, but since `addrspacecast` fails perhaps there's also a bug in the static initialization functions?
It's a long shot, but I'll look more into compiling coriander with 5.0 today by hacking away at the type conversions and update this post accordingly.

I have a docker file and Jupyter workbook for reproducibility, if either/both of you were interested in helping fix this or collaborating on my "Towards language-agnostic architecture-independent workload characterization" paper?

**Comment by jrprice** [comment]
> Without looking into the llvm source code, but since addrspacecast fails perhaps there's also a bug in the static initialization functions?

These are two different issues - the static initialization problem exists with all versions of LLVM unfortunately. FWIW 4.0.1 fixes the addrspacecast bug, and I presume coriander would build with that.

Another thing to try would be to get both Oclgrind and coriander to *dynamically* link to the same version of LLVM, which I think may solve the issue. This should be relatively straightforward for Oclgrind (possibly with a minor tweak to the CMake config).

**Comment by BeauJoh** [comment]
Thanks @jrprice you're spot on!

I got both Oclgrind and Coriander to dynamically link to the same version of LLVM.
I've created a [Github repo](https://github.com/BeauJoh/coriander-and-oclgrind) complete with a [dockerfile](https://raw.githubusercontent.com/BeauJoh/coriander-and-oclgrind/master/Dockerfile) to outline all the steps of how this was achieved.
I should probably also make a pull request to each of your projects to keep our work in-sync. There were only very minor changes needed to get them to both dynamically link.

If you want to check out my public binary build you can test it out on your codes with:

    docker run --rm -it --runtime=nvidia beaujoh/coriander-and-oclgrind:1.0

Let me know if either of you would like to collaborate on a Language-Agnostic Architecture-Independent Workload Characterization paper -- using both your tools has been critical to the investigation.
